# Generated by Django 5.1.1 on 2025-03-21 10:17

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.TextField(blank=True, max_length=50, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, help_text='Unique identifier for the chat with the user', null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            managers=[
                ('admins', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, verbose_name='Config data')),
                ('activated', models.BooleanField(verbose_name='Is active config')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vpn.client')),
            ],
        ),
    ]
