start_created = "Sup, {first_name}!"
start_not_created = "Welcome back, {first_name}!"

CREATE_VPN = "Create VPN"
MY_VPN = "My VPN"
MY_BALANCE = "My balance"
DEPOSIT = "Deposit"
PRICE = "Price"
HELP = "Help"
REFERRAL = "Referral"
