version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: db_postgres
    restart: always
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5434:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: always
    command: bash -c "poetry run python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot_app
    restart: always
    command: poetry run python run_polling.py
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  postgres_data:
