# Generated by Django 5.0.8 on 2025-02-27 17:43

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VPNConfig',
            fields=[
                ('id', models.PositiveBigIntegerField(help_text="Config's ID", primary_key=True, serialize=False)),
                ('private_key', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=50)),
                ('public_key', models.CharField(max_length=64)),
                ('allowed_ips', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('endpoint', models.CharField(max_length=100)),
                ('persistent_keepalive', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vpn_configs', to='users.user')),
            ],
        ),
    ]
