# Generated by Django 5.0.8 on 2025-02-27 17:43

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=True, max_length=50, null=True)),
                ('chat_id', models.IntegerField(blank=True, help_text='Unique identifier for the chat with the user', null=True, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
            managers=[
                ('admins', django.db.models.manager.Manager()),
            ],
        ),
    ]
