# Generated by Django 5.0.8 on 2025-03-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text='Unique identifier for the chat with the user', null=True, unique=True),
        ),
    ]
